language: bash
services: docker

env:
  - VERSION=latest

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="yongjhih/parse-dashboard:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
language: node_js
node_js:
  - "4.3"
  - "4.4"
  - "5.7"
  - "6.1"
